---
- hosts: servers
  tasks:
  - name: Install Docker
    apt:
      name: docker.io
      state: present
  - name: Pull the application image
    docker_image:
      name: my-project:test
      source: pull
  - name: Run the application container
    docker_container:
      name: my-project
      image: my-project:test
      ports:
        - 3000:3000